from sqlalchemy import Column, Integer, String, Text, DateTime, Boolean
from datetime import datetime

from database import Base


class PatientSymptoms(Base):
    __tablename__ = "patient_symptoms"

    # ---------------------------------------------------------
    # Primary key
    # ---------------------------------------------------------

    id = Column(
        Integer,
        primary_key=True,
        index=True
    )

    # ---------------------------------------------------------
    # Patient reference
    # Example: 18/2026
    # ---------------------------------------------------------

    patient_id = Column(
        String,
        nullable=False,
        index=True
    )

    # ---------------------------------------------------------
    # Original symptoms entered by the patient
    # ---------------------------------------------------------

    symptoms = Column(
        Text,
        nullable=False
    )

    # ---------------------------------------------------------
    # Questions generated by Nemotron
    #
    # Stored as JSON text.
    # ---------------------------------------------------------

    generated_questions = Column(
        Text,
        nullable=True
    )

    # ---------------------------------------------------------
    # Answers submitted by the patient
    #
    # Stored as JSON text.
    # ---------------------------------------------------------

    answers = Column(
        Text,
        nullable=True
    )

    # ---------------------------------------------------------
    # Family / household history
    #
    # Example:
    # "Yes - mother has similar symptoms"
    # ---------------------------------------------------------

    family_history = Column(
        Text,
        nullable=True
    )

    # ---------------------------------------------------------
    # Whether the patient has previously taken medication
    #
    # True  = Yes
    # False = No
    # None  = Not answered yet
    # ---------------------------------------------------------

    previous_medication = Column(
        Boolean,
        nullable=True
    )

    # ---------------------------------------------------------
    # Path of uploaded previous prescription
    #
    # This is optional.
    # ---------------------------------------------------------

    prescription_path = Column(
        String,
        nullable=True
    )

    # ---------------------------------------------------------
    # Original filename of uploaded prescription
    # ---------------------------------------------------------

    prescription_original_name = Column(
        String,
        nullable=True
    )

    # ---------------------------------------------------------
    # Path of generated patient summary DOCX
    # ---------------------------------------------------------

    summary_path = Column(
        String,
        nullable=True
    )

    # ---------------------------------------------------------
    # Original filename of generated summary
    # ---------------------------------------------------------

    summary_original_name = Column(
        String,
        nullable=True
    )

    # ---------------------------------------------------------
    # Record creation time
    # ---------------------------------------------------------

    created_at = Column(
        DateTime,
        default=datetime.utcnow
    )